### ISSUE TITLE
http 500 with trello progress api ?

### ISSUE THREAD

**Issue by xinity** [sep/ollert#18]
hi,

i'm trying to use ollert locally (using a linux vm as a server) i've followed requirements and everything seems to be starting correctly.
when ollert is authorized on trello (private dashboard), i have this message log:
GET /api/v1/progress/[....] HTTP/1.1" 500 70575 0.9488

and i have plenty of these on screen:
'''
"<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html lang="en"> <head> <meta http-equiv="content-type" content="text/html; charset=utf-8" /> <meta name="robots" content="NONE,NOARCHIVE" /> <title>NoMethodError at &#x2F;api&#x2F;v1&#x2F;progress&#x2F;54f6bd99e0c4279960a5e705</title> <style type="text/css"> html * { padding:0; margin:0; } body * { padding:10px 20px; } body * * { padding:0; } body { font:small sans-serif; } body>div { border-bottom:1px solid #ddd; } h1 { font-weight:normal; } h2 { margin-bottom:.8em; } h2 span { font-size:80%; color:#666; font-weight:normal; } h3 { margin:1em 0 .5em 0; } h4 { margin:0 0 .5em 0; font-weight: normal; } table { border:1px solid #ccc; border-collapse: collapse; background:white; } tbody td, tbody th { vertical-align:top; padding:2px 3px; } thead th { padding:1px 6px 1px 3px; background:#fefefe; text-align:left; font-weight:normal; font-size:11px; border:1px solid #ddd; } tbody th { text-align:right; color:#666; padding-right:.5em; } table.vars { margin:5px 0 2px 40px; } table.vars td, table.req td { font-family:monospace; } table td.code { width:100%;} table td.code div { overflow:hidden; } table.source th { color:#666; } table.source td { font-family:monospace; white-space:pre; border-bottom:1px solid #eee; } ul.traceback { list-style-type:none; } ul.traceback li.frame { margin-bottom:1em; } div.context { margin: 10px 0; } div.context ol { padding-left:30px; margin:0 10px; list-style-position: inside; } div.context ol li { font-family:monospace; white-space:pre; color:#666; cursor:pointer; } div.context ol.context-line li { color:black; background-color:#ccc; } div.context ol.context-line li span { float: right; } div.commands { margin-left: 40px; } div.commands a { color:black; text-decoration:none; } #summary { background: #ffc; } #summary h2 { font-weight: normal; color: #666; } #summary ul#quicklinks { list-style-type: none; margin-bottom: 2em; } #summary ul#quicklinks li { float: left; padding: 0 1em; } #summary ul#quicklinks>li+li { border-left: 1px #666 solid; } #explanation { background:#eee; } #template, #template-not-exist { background:#f6f6f6; } #template-not-exist ul { margin: 0 0 0 20px; } #traceback { background:#eee; } #requestinfo { background:#f6f6f6; padding-left:120px; } #summary table { border:none; background:transparent; } #requestinfo h2, #requestinfo h3 { position:relative; margin-left:-100px; } #requestinfo h3 { margin-bottom:-1em; } .error { background: #ffc; } .specific { color:#cc3300; font-weight:bold; } </style> <script type="text/javascript"> // </script> </head> <body> <div id="summary"> <h1>NoMethodError at &#x2F;api&#x2F;v1&#x2F;progress&#x2F;54f6bd99e0c4279960a5e705</h1> <h2>undefined method `join&#x27; for #&lt;String:0x000000060e3ac0&gt;</h2> <table><tr> <th>Ruby</th> <td> <code>&#x2F;usr&#x2F;local&#x2F;rvm&#x2F;gems&#x2F;ruby-2.2.0&#x2F;gems&#x2F;sinatra-1.4.5&#x2F;lib&#x2F;sinatra&#x2F;show_exceptions.rb</code>: in <code>rescue in call</code>, line 37 </td> </tr><tr> <th>Web</th> '''

any clues maybe ?

Thanks :)

**Comment by larryprice** [comment]
Hi - can you post the console log associated with the failure?

**Comment by xinity** [comment]
here it is:
'''
10:15:44 web.1  |         Called from: /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:86:in `new'.
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /js/jquery-2.1.1.min.js HTTP/1.1" 304 - 0.0021
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /js/bootstrap.min.js HTTP/1.1" 304 - 0.0016
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /js/underscore-min.js HTTP/1.1" 304 - 0.0015
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /js/trello-client.js HTTP/1.1" 304 - 0.0015
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /css/bootstrap.min.css HTTP/1.1" 304 - 0.0271
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /styles.css HTTP/1.1" 200 - 0.0608
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /js/ollert.js HTTP/1.1" 304 - 0.0018
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /js/time-tracker.js HTTP/1.1" 304 - 0.0017
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /js/flash-message.js HTTP/1.1" 304 - 0.0016
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /js/trello-controller.js HTTP/1.1" 304 - 0.0186
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /js/plugins.js HTTP/1.1" 304 - 0.0047
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /img/SEP-Labs-Logo-White.svg HTTP/1.1" 304 - 0.0023
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /fonts/muli.woff HTTP/1.1" 304 - 0.0012
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /fonts/glyphicons-halflings-regular.woff HTTP/1.1" 304 - 0.0009
10:15:44 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:44 +0000] "GET /img/ollert-logo-white.svg HTTP/1.1" 304 - 0.0027
10:15:45 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:45 +0000] "GET /boards HTTP/1.1" 200 - 0.6339
10:15:53 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:53 +0000] "GET /boards/54f6bd35e0c4279960a5e705 HTTP/1.1" 200 - 0.5720
10:15:53 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:53 +0000] "GET /styles.css HTTP/1.1" 200 - 0.0255
10:15:54 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:54 +0000] "GET /boards HTTP/1.1" 200 - 0.4044
10:15:54 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:54 +0000] "GET /api/v1/labels/54f6bd35e0c4279960a5e705?token=85f80f7ff473e7312eb3c4d2f4f02908cfb1cf3a4eb600ff8b33d0527d0947bb HTTP/1.1" 200 - 0.2543
10:15:54 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:54 +0000] "GET /api/v1/wip/54f6bd35e0c4279960a5e705?token=85f80f7ff473e7312eb3c4d2f4f02908cfb1cf3a4eb600ff8b33d0527d0947bb HTTP/1.1" 200 - 0.7575
10:15:55 web.1  | Encoding::InvalidByteSequenceError - "\xC3" on US-ASCII:
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `encode'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
10:15:55 web.1  |       /srv/ollert/utils/fetchers/stats_fetcher.rb:24:in `fetch'
10:15:55 web.1  |       /srv/ollert/routes/analysis_routes.rb:54:in `block in <class:Ollert>'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1602:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1602:in `block in compile!'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-flash3-1.0.5/lib/rack/flash.rb:124:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/chunked.rb:54:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/bin/unicorn:23:in `load'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/bin/unicorn:23:in `<main>'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
10:15:55 web.1  | NoMethodError: undefined method `join' for #<String:0x00000005414c18>
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/chunked.rb:54:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/bin/unicorn:23:in `load'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/bin/unicorn:23:in `<main>'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
10:15:55 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:55 +0000] "GET /api/v1/progress/54f6bd35e0c4279960a5e705?startingList=54f6bd82e0c4279960a5e32d&endingList=54f6bd82e0c4279960a5e329&token=85f80f7ff473e7312eb3c4d2f4f02908cfb1cf3a4eb600ff8b33d0303d0947bb HTTP/1.1" 500 70694 0.7848
10:15:55 web.1  | 172.17.42.1 - - [13/Jul/2015:10:15:55 +0000] "GET /api/v1/listchanges/54f6bd35e0c4279960a5e705?token=85f80f7ff473e7312eb3c4d2f4f02908cfb1cf3a4eb600ff8b33d0527d0947bb HTTP/1.1" 200 - 1.0573
'''

**Comment by larryprice** [comment]
Isolating the error seems to lead me here:

```
10:15:55 web.1  | Encoding::InvalidByteSequenceError - "\xC3" on US-ASCII:
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `encode'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'
10:15:55 web.1  |       /usr/local/rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
10:15:55 web.1  |       /srv/ollert/utils/fetchers/stats_fetcher.rb:24:in `fetch'
10:15:55 web.1  |       /srv/ollert/routes/analysis_routes.rb:54:in `block in <class:Ollert>'
```

Can you reproduce this issue in production?

**Comment by xinity** [comment]
what do you mean by production ?
it's my first try of ollert and as today , i launch it using : rake start 

don't even know how to put it in production mode 

any clues maybe?

**Comment by larryprice** [comment]
By production I mean can you reproduce it on the main site: https://ollertapp.com

**Comment by xinity** [comment]
just tried 

it works perfectly without any glitch

**Comment by larryprice** [comment]
OK, great. Are you interested in hacking on Ollert or do you just want to use the application? If you just want to use the application, I recommend sticking with the production site.

If you want to hack, that's also great, but we'll need to figure out why your system is trying to use US-ASCII to generate the JSON. We might be able to make some headway if you can describe your system details: OS version, ruby version, locale, etc.

**Comment by xinity** [comment]
actually both.
we'd like to have an on-premise installation of ollert and hack into it later on :)

system OS: ubuntu 14.04LTS
ruby version : ruby 2.2.0p0
locale: "POSIX" <=== that might be the reason ?

**Comment by larryprice** [comment]
Any reason in particular that you want a local installation over using the main site?

What are your results of running `locale` on your machine? I get the following information:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by xinity** [comment]
for the on-premise, this is an internal rule, we'd like to keep control over our data flow.

**Comment by xinity** [comment]
works like a charm when using the right locale :)
