### ISSUE TITLE
Charts use Lucida Grande/Helvetica rather than Muli

### ISSUE THREAD

**Issue by heybenji** [sep/ollert#19]
Just a quick thing, Highcharts (public/js/highstock.js) seems to be injecting an inline style on the SVGs of the charts that makes them display in Lucida Grande (or Arial/Helvetica, on Windows/Linux) rather than Muli.

I'd submit a pull request but there would be two approaches:

1. Remove the declaration `fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',` from line 55 of public/js/highstock.js or
2. Include a declaration in your CSS of `.highcharts-container svg { font-family: 'Muli', sans-serif !important; }`

I you let me know which one you prefer, I can submit a pull request with the change, or it seems simple enough to make.

I have some other small visual enhancements I worked up if you're interested. If so, I'll happily submit a pull request for that, though I may need a little help getting a dev environment set up.

Benji

**Comment by larryprice** [comment]
Hi Benji - Option 2 is the preferred option. Submit a PR when you get the chance. If you're struggling to get a dev env up and running you're free to mention it here as well. As for the other "visual enhancements", I wouldn't mind seeing an issue created with a shortlist of some of the things you'd like to address, at which point we can discuss it further. Looking forward to the PR!
