### ISSUE TITLE
Analyze archive cards

### ISSUE THREAD

**Issue by roy2006** [sep/ollert#49]
Hi, 

Overall, I think it's a great project - thanks for building it. One thing - as our board gets crowded, we often archive old 'done' cards. As far as I understand, you don't analyze archived cards. Would it be possible to add an option to do that? 

Thanks in advance.

**Comment by deanott** [comment]
Agreed, I often archive many cards and replace them with several new cards. Would be interesting to see how easy would be to view details about the archived cards.

**Comment by larryprice** [comment]
Do you think we should include or exclude archived cards by default? I'm back and forth on the issue, but currently leaning towards exclusion with a checkbox in the settings to toggle.

**Comment by deanott** [comment]
Personally not by default, in my boards I think seeing archived cards regularly would ruin my burns and not show truely what I'm getting through. Plus much of the archived cards I see by other people are sometimes mistakes that just never get deleted...

**Comment by roy2006** [comment]
I would include them by default, as one would typically like to get a full
view of the data when he's running reports. That being said, I don't think
it's critical as long as there's a checkbox.

**Comment by larryprice** [comment]
This is *mostly* done except I need to fix a bunch of tests and things. I expect this to be in by Monday night.
